dist: trusty
sudo: false
notifications:
  email: false
language: node_js
node_js:
  - "8"

cache:
  directories:
    - node_modules
    - $HOME/.m2

before_install:
  # sdkman helps to install different maven versions
  - curl -s "https://get.sdkman.io" | bash
  - source "$HOME/.sdkman/bin/sdkman-init.sh"
  - echo sdkman_auto_answer=true > ~/.sdkman/etc/config
  # install jdk is needed for JDK10+
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

jobs:
  include:
    - stage: Node versions + actual Maven version
      node_js: 8
      env: MAVEN_VERSION=3.6.1 JDK=10
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    -
      node_js: 10
      env: MAVEN_VERSION=3.6.1 JDK=11
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    - stage: Older Maven version
      env: MAVEN_VERSION=3.3.9 JDK=8
      script:
        - jdk_switcher use openjdk8
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    -
      env: MAVEN_VERSION=3.3.9 JDK=9
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    -
      env: MAVEN_VERSION=3.3.9 JDK=10
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    -
      env: MAVEN_VERSION=3.3.9 JDK=11
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    -
      env: MAVEN_VERSION=3.3.9 JDK=12
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    -
      env: MAVEN_VERSION=3.3.9 JDK=13
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    -
      env: MAVEN_VERSION=3.6.1 JDK=8
      script:
        - jdk_switcher use openjdk8
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    -
      env: MAVEN_VERSION=3.6.1 JDK=12
      script:
        - source install-jdk.sh --feature $JDK
        - ln -sf /etc/ssl/certs/java/cacerts $JAVA_HOME/lib/security/cacerts
        - sdk install maven $MAVEN_VERSION
        - java -version
        - npm test
    - stage: npm release
      if: branch = master
      node_js: "8" # This *has* to be the "build leader"
      script: skip
      after_success:
        - npx semantic-release